Create pinning file during publishing
ynput/ayon-usd pull request #41
Opened 2024-09-06 20:45 UTC by antirotor

## Changelog Description
Introducing new extractor and integrator to create usd pinning file during publishing. To simplify things, this uses two plugins - extractor just runs to create almost empty json file so it can be integrated in regular way. Then there is integrator that will push the generated version pins to the json file that is run after everything else was already integrated.

## Additional info
This is using some code borrowed from https://github.com/ynput/ayon-usd/pull/29 and some from https://github.com/ynput/ayon-core/blob/develop/client/ayon_core/plugins/publish/extract_usd_layer_contributions.py

This needs definitely some cleanup and code moving before the merge, therefor this PR will be just Draft until then.

## Testing notes:

1. publish usd product from any DCC
2. if extract pinning file is enabled, it will produce it

2024-09-17 06:39 UTC, Lypsolon requested changes
this file `integrate_pinning_file` has the same functions as `_pinning_file_generation_funcs` aka the pinning module in standalone libs. 

please use the module from standalone it has been build this way to make it easy to build automated tests for it. 

client/ayon_usd/plugins/publish/integrate_pinning_file.py

client/ayon_usd/standalone/usd/pinning/_pinning_file_generation_funcs.py

2024-09-17 07:48 UTC, Lypsolon requested changes

2024-09-17 07:48 UTC, Lypsolon commented on client/ayon_usd/plugins/publish/integrate_pinning_file.py
> +        return filepath
```suggestion
    def _save_usd_from_houdini(self, instance: pyblish.api.Instance) -> Path:
        """Save USD file from Houdini.

        Args:
            instance (pyblish.api.Instance): Instance object.

        Returns:
            str: The rootless path to the saved USD file.

        """
        import hou
        from ayon_houdini.api import maintained_selection

        ropnode = hou.node(instance.data.get("instance_node"))
        filename = ropnode.parm("lopoutput").eval()
        directory = ropnode.parm("savetodirectory_directory").eval()
        filepath = Path(directory) / filename

        # create temp usdrop node
        with maintained_selection():
            temp_usd_node = hou.node("/out").createNode("usd")
            temp_usd_node.parm("lopoutput").set(
                filepath.as_posix())
            temp_usd_node.parm("loppath").set(ropnode.parm("loppath").eval())
            temp_usd_node.render()
            temp_usd_node.destroy()

        return filepath
        
    def save_usd(self, instance: pyblish.api.Instance) -> Path:
        """Save USD file to disk.

        Args:
            instance (pyblish.api.Instance): Instance object.

        Returns:
            str: The rootless path to the saved USD file.

        """
        if get_current_host_name() == "houdini":
            return self._save_usd_from_houdini(instance)
        raise NotImplementedError(
            f"Unsupported host {get_current_host_name()}")
```

i believe those 2 functions need to be defined in a rotated order so that a linter can follow them. 

also i believe save_usd() should crash as _save_usd_from_houdini() is defined later no ?

2024-09-17 07:48 UTC, Lypsolon commented on client/ayon_usd/plugins/publish/integrate_pinning_file.py
> +    return True
this is also from the standalone library please import it form there so we dont have to maintain it multiple times.

2024-09-17 07:48 UTC, Lypsolon commented on client/ayon_usd/plugins/publish/integrate_pinning_file.py
> +    return identifier_to_path_dict
this is from the standalone library

2024-09-17 07:48 UTC, Lypsolon commented on client/ayon_usd/plugins/publish/integrate_pinning_file.py
> +    return udim_data
this is from the standalone library

2024-09-17 07:48 UTC, Lypsolon commented on client/ayon_usd/plugins/publish/integrate_pinning_file.py
> +    return resolver.Resolve(abs_path)
this is from the standard library

2024-09-17 07:48 UTC, Lypsolon commented on client/ayon_usd/plugins/publish/integrate_pinning_file.py
> +    return re.sub(re.compile(r":SDF_FORMAT_ARGS.*$"), "", ref)
this is also from the standalone lib

2024-09-17 07:48 UTC, Lypsolon commented on client/ayon_usd/plugins/publish/integrate_pinning_file.py
> +        generate_pinning_file(
please import from standalone library.

2024-09-17 08:53 UTC, antirotor commented on client/ayon_usd/plugins/publish/integrate_pinning_file.py
> +        return filepath
since they are in class, it doesn't matter

2024-09-17 12:29 UTC, antirotor commented
I've removed all duplicated and unused functions and also fixed some issue in the standalone libs regarding handling of pinning data dict on windows.

2024-09-17 23:59 UTC, BigRoy commented on client/ayon_usd/hooks/usd_pinning_root.py
> +    launch_types: ClassVar = {LaunchTypes.farm_publish}
This `ClassVar` type hint should really be set on the `PreLaunchHook` base class, no?

2024-09-17 23:59 UTC, BigRoy commented on client/ayon_usd/standalone/usd/pinning/_pinning_file_generation_funcs.py
> +    pinning_data = normalized_data
You are now basically breaking other platforms than windows because `pinning_data` will then always be `{}`?

2024-09-17 23:59 UTC, BigRoy commented on client/ayon_usd/plugins/publish/integrate_pinning_file.py
> +        return filepath
Oh boy - this goes against ALL the concepts of Houdini - why do we need a temporary rop node to do a temporary export, etc? This seems _very fishy_

2024-09-18 07:17 UTC, antirotor commented on client/ayon_usd/plugins/publish/integrate_pinning_file.py
> +        return filepath
So how would you get USD file from the current state in houdini so the `generate_pinning_json()` will process it? I realize that this is fishy but it comes back to the fact that we need to create the pinning during the publishing but the USD is produced on farm. If there is better way to directly get the USD file from `usdrender` node, or just create new USD stage from the LOP path specified there, I would go for it.

2024-09-18 07:20 UTC, antirotor commented on client/ayon_usd/standalone/usd/pinning/_pinning_file_generation_funcs.py
> +    pinning_data = normalized_data
right you are. fixed

2024-09-18 07:27 UTC, antirotor commented on client/ayon_usd/hooks/usd_pinning_root.py
> +    launch_types: ClassVar = {LaunchTypes.farm_publish}
**TL;DR:** yes, it should be on the base class, I did it here to calm my ruff settings and I didn't want to create arbitrary PR to ayon-applications addon before we standardize ruff setings.

This stems from the rules we are ignoring in ruff settings. I was playing with rules that are more restrictive and that we should enforce later to all repos but that is work for more systematic approach to ruff settings (and we need to get list of those exceptions that we don't want to enforce - there is a lot of them).

2024-09-19 20:02 UTC, BigRoy commented on client/ayon_usd/plugins/publish/integrate_pinning_file.py
> +        return filepath
We'll leave this for later.

2024-09-19 20:08 UTC, BigRoy approved these changes
Since we're in experimental I'll approve this - but there are issues we need to solve down the line.

1. One may want to use `ayon-usd` without this, however it cannot be disabled currently. Although it is _optional_ on the plugin itself? Maybe even weirder that both the extractor and integrator are separately optional?
2. The `ClassVar` type hint across 'inherited attributes' from other libraries seems odd?

2024-09-19 20:08 UTC, BigRoy commented on client/ayon_usd/utils.py
> +        pathlib.Path: Path to the pinning file.
```suggestion
        pathlib.Path | None: Path to the pinning file.
```

2024-09-20 08:00 UTC, antirotor commented
> Since we're in experimental I'll approve this - but there are issues we need to solve down the line.
> 
> 1. One may want to use `ayon-usd` without this, however it cannot be disabled currently. Although it is _optional_ on the plugin itself? Maybe even weirder that both the extractor and integrator are separately optional?
> 2. The `ClassVar` type hint across 'inherited attributes' from other libraries seems odd?

I've removed `ClassVar`, took the opportunity to remove also some forgotten debug prints and I've made only the Extractor optional. WIthout the Extractor, Integrator wouldn't trigger too so with that, you can enable/disable pinning on publish.

@Lypsolon there is still changers required pending. Should I dismiss your review or will you approve too?

2024-09-20 12:25 UTC, Lypsolon commented
> > Since we're in experimental I'll approve this - but there are issues we need to solve down the line.
> > 
> > 1. One may want to use `ayon-usd` without this, however it cannot be disabled currently. Although it is _optional_ on the plugin itself? Maybe even weirder that both the extractor and integrator are separately optional?
> > 2. The `ClassVar` type hint across 'inherited attributes' from other libraries seems odd?
> 
> I've removed `ClassVar`, took the opportunity to remove also some forgotten debug prints and I've made only the Extractor optional. WIthout the Extractor, Integrator wouldn't trigger too so with that, you can enable/disable pinning on publish.
> 
> @Lypsolon there is still changers required pending. Should I dismiss your review or will you approve too?

you can just dismiss me no problem.

2024-09-20 12:26 UTC, Lypsolon approved these changes

2024-09-20 16:50 UTC, antirotor commented on client/ayon_usd/plugins/publish/integrate_pinning_file.py
> +            ayon_api.get_project_roots_by_site_id(get_current_project_name()),
There is issue with serveral similar calls that are basically deprecated. This one is the one to use to get all roots.

2024-09-20 16:50 UTC, merged