added a popup we wait on when you did not agree to the experimentals
ynput/ayon-usd pull request #43
Opened 2024-09-12 11:06 UTC by Lypsolon

## Changelog Description
this branches away from  pinning file support and adds the popup. 

## Additional info

## Testing notes:

2024-09-12 11:12 UTC, antirotor requested changes
I don't think we can do it that way - addons are initialized even on headless machines (render machines) so any code importing `QtWidgets` will fail there. Also the import in `addon.py` is unnecessary?

2024-09-12 11:29 UTC, Lypsolon commented
> I don't think we can do it that way - addons are initialized even on headless machines (render machines) so any code importing `QtWidgets` will fail there. Also the import in `addon.py` is unnecessary?

yes we need an function that tells us if qt is availalbe so that we can guard the imports. 
but i was not able to figure out how to do that without the linter hating me. 

if i do (code out of the back of my head) 
HEADLESS_MODE = True
try: 
import qt 
HEADLESS_MODE = False
except: 
print("info")

if not HEADLESS_MODE: 
   import qt related things 
   
   
if not HEADLESS_MODE: 
   run the function that creates the popup. 
   
then he errors because there are things about the top layer import. 

btw iLLiCiTiT already marked it but the addon cant start headless because lakefs gui import also needs qt. 

but i was not able to find out how to do it.

2024-09-12 11:39 UTC, Lypsolon commented
@antirotor you brought up this idea
`HEADLESS_MODE_ENABLED = os.getenv("AYON_HEADLESS_MODE") == "1"` 
in the other branch. 

do we know it headless mode is a guarantee? because there are no Docs for it what so ever.

2024-09-12 11:43 UTC, antirotor commented
I actually don't know - I don't think that there is really any qt based check - this env var is set if you explicitly run ayon with `--headless` flag and that we should definitely respect. Maybe @iLLiCiTiT know if we check for the UI capability somewhere?

2024-09-12 11:47 UTC, BigRoy commented on package.py
> +version = "0.1.0-alpha-dev-pop1"
This per PR versioning is actually quite cumbersome (and I feel redundant too). Can we avoid that or is there a need to do so from your end? Other addon repos don't do that, but only version up on releases.

2024-09-12 11:47 UTC, iLLiCiTiT commented
We don't, we can't. There is function `is_headless_mode_enabled`. If that returns `True` you should never get to point that you import anything from Qt.

2024-09-12 11:48 UTC, BigRoy commented
Please bear in mind @mkolar 's comment:

> This is overkill. Give a notice in the settings or whereever they are guaranteed to see it at least once and that's it. I wouldn't be adding explicit checkboxes.

The important bit in that point is the "must see at least once". I'd argue that with how the system is currently designed (and one being required to configure the LakeFS settings) that one MUST access the settings page regardless. So, we may be best off when that checkbox is disabled to just log a command-line warning and documentation and live with that.

Whether that suffices to what @dee-ynput wanted here - I'll let the battle commence here.

2024-09-12 11:48 UTC, iLLiCiTiT commented on client/ayon_usd/utils.py
> +    app = QtWidgets.QApplication()
Unless you run this in subprocess, you can't create `QApplication` and call `quit` on it.

2024-09-12 11:51 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +from ayon_usd import HEADLESS_MODE_ENABLED
```suggestion
from ayon_core.lib import is_in_headless_mode
```

2024-09-12 11:52 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
>              raise SystemError(
Why `SystemError` is raised here?

2024-09-12 11:52 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +            if not HEADLESS_MODE_ENABLED:
This should happen probably only in `tray_init`?

2024-09-12 11:53 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +            controller.start()
Do you need to start the progress on addon initialization (Addon initialization can happen a lot during single process lifetime.)?

2024-09-12 11:55 UTC, Lypsolon commented on package.py
> +version = "0.1.0-alpha-dev-pop1"
i did it so i can find it easy on the server. 
because different dev branches use the same numbers or the numbers arent in order. aka branch A -dev.78 and B -dev.77 but they have no relation to each other and jumping between them is a PITA 

or do you mean the -alpha flag ? 
this we allready talked about. its there because most addons just ignore how SemVar versions things and i want people to understand that they are running an alpha version of an addon. 
usually this should be clear as semvar defines that 0.x.x is alpha and 1.x.x is first actual release, 
but eighter all the tools we have run in alpha or they dont follow SemVar correctly.

2024-09-12 11:56 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +    from qtpy import QtWidgets
These imports should happen in the methods that need them.

2024-09-12 12:03 UTC, Lypsolon commented on client/ayon_usd/addon.py
>              raise SystemError(
well could be any error. 
the reason an error is raised is because we have a button you need to agree to in the settings and if you dont agree to the terms of an addon beeing experimental you cant start it. 

on the question why System
the decision was between System and Runtime. 
we could use seomting else or implement someting, but System dose the job and its an uncommon error. 
Runtime would be the wrong one as its not an Error related to the Runtime (its also not an error with the System sooo yeah)

2024-09-12 12:05 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +            if not HEADLESS_MODE_ENABLED:
we wanted it as early as possible as its the first thing that should happen when the addon starts. 

if this is false we dont need to do anything with the addon just have it crash so there is info in the log and then dont enable it.

2024-09-12 12:06 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +            download_ui = progress_ui.ProgressDialog(
i asked a good while ago if this should be in init because we need to download usd and libs also i all places for eg farm etc. 

and i believe tray init dosnt run on farm but this is how it was merged in the end.

2024-09-12 12:08 UTC, iLLiCiTiT commented on client/ayon_usd/utils.py
> +    app = QtWidgets.QApplication()
QApplication should not be created more than once because it is singleton, and quiting here will remove flags and delete some cache that is not re-set back when new instance is initialized, so you should not do it unless you're in subprocess.

2024-09-12 12:08 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +from ayon_usd import HEADLESS_MODE_ENABLED
so there this function dose make this grantee.

2024-09-12 12:12 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +
```suggestion
```

2024-09-12 12:17 UTC, iLLiCiTiT commented on client/ayon_usd/utils.py
> +def info_popup(title: str, message: str):
```suggestion

def info_popup(title: str, message: str):
```

2024-09-12 12:18 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +from ayon_usd import HEADLESS_MODE_ENABLED
> so there this function dose make this grantee.

I don't understand the sentece?

2024-09-12 12:20 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +                utils.info_popup("Ayon Usd Addon", "The experimental AyonUsd addon is currently activated, "
```suggestion
                utils.info_popup(
                    "AYON USD addon",
                    "The experimental AYON USD addon is currently activated, "
```

2024-09-12 12:24 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +from ayon_usd import HEADLESS_MODE_ENABLED
did you rename this function ? 

0.4.5 has it but as `is_headless_mode_enabled`

or is it new ? 
looks like this is recent ? 
https://github.com/ynput/ayon-core/blob/develop/client/ayon_core/lib/__init__.py
`[iLLiCiTiT](https://github.com/ynput/ayon-core/commits?author=iLLiCiTiT)
iLLiCiTiT
[added 'is_headless_mode_enabled' function](https://github.com/ynput/ayon-core/commit/92ce331a302c26a6a9a9fd47361269225d07b098)`

2024-09-12 12:26 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +from ayon_usd import HEADLESS_MODE_ENABLED
Ah, yes, wrong name.

2024-09-12 12:26 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +            download_ui = progress_ui.ProgressDialog(
Moving conversation here https://github.com/ynput/ayon-usd/pull/43#discussion_r1756709875

2024-09-12 12:28 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +            controller.start()
Can you find out if it is necessary to do anything before you start the controller?

If there is nothing to do then implementation could be something like:
```python
if controller.nothing_to_download:
    return
```
Before any widget is shown or logic is started.

2024-09-12 12:32 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +            if not HEADLESS_MODE_ENABLED:
I'm talking about showing the dialog. That's related to the fact that addon is initializated at multiple places, and possibly multiple times, most of them are not in headless mode, so user will have to close this dialog 5 times before he can do anything, and then it will show up again on publishing start.

2024-09-12 12:33 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +from ayon_usd import HEADLESS_MODE_ENABLED
done

2024-09-12 12:37 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +            if not is_headless_mode_enabled():
Conversation lost on change:
https://github.com/ynput/ayon-usd/pull/43#discussion_r1756768450

2024-09-12 12:38 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +            controller.start()
kinda dosnt metter tbh. 
we check if the libs are downloaded so we kinda dont care in the end it needs to happen once as early as possible so we dont have to think about it later after that the checks will take care. 

in best case we would have something that only gets called when the addon is initialized at startup. 

also what dose a lot mean do we talk 100million times because with 20times we can just trust the download checks if we talk millions different story.

2024-09-12 12:42 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +    from qtpy import QtWidgets
nope the methods should not import anything. 
first of all because the this causes more deduplication requests for the import system but also because pep says it. 

https://peps.python.org/pep-0008/#imports
```
Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.
```

we could add into the doc sting of the popup function that this its the callers job to check for the qt availability but this is already implied.

2024-09-12 12:43 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +
done via external commit.

2024-09-12 12:43 UTC, Lypsolon commented on client/ayon_usd/utils.py
> +def info_popup(title: str, message: str):
done via external commit.

2024-09-12 12:44 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +            controller.start()
You're showing dialog with progress 20 times. That's a problem. I don't know what the logic of the dialog is, if it is similar to what you have right now in info dialog, then it is huge problem.

2024-09-12 12:45 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +    from qtpy import QtWidgets
Pep is recommendation not bible.

2024-09-12 12:46 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +                utils.info_popup("Ayon Usd Addon", "The experimental AyonUsd addon is currently activated, "
done in external commit.

2024-09-12 12:49 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +            if not is_headless_mode_enabled():
im gonna close the otter comment and would ask you to describe why this comment is here ?

2024-09-12 12:55 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +            if not is_headless_mode_enabled():
If `"allow_addon_start"` is set to `False` it will show dialog (from what I see). But it will happen on every initialization of addon. That's a lot of dialogs to close. The dialog should be shown only in `tray_init`, not on every initialization of addon.

2024-09-12 13:14 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +    from qtpy import QtWidgets
**i disagree.**
i follow the convention that as long as Ynput dose not define its own standard the Language standard is to be uphold as much as possible. 

and in this case its more than just possible we could use meta "programming" and if-guard all the functions that need those imports and then write into the doc-stings that they are if-guarded. 


also yes this is a standard python application. what we do is not magic it simply isn't ,following the standards is not impossible or implausible.  

on top of all that, we are special is not an argument, if you want something to be done a special way i will need specific arguments why this method is valid and all the possible implications. on top of that non standard behavior needs to be documented. 

**a few things about if-guarding**

i believe if-guarding imports is better than functions as if-guarded functions mean that you have to dubble if-guard (first the caller needs to if-guard the function call then the function itself needs to if-guard) 
this can be avoided by if-guarding the function definition as this will be resolved at import just as the the guarded import. 

in compiled languages this would be a bit more practice as macro programming would allow the removal of code blocks. non the less python still allows for this conversion and dose it efficient enough.

2024-09-12 13:15 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +            if not is_headless_mode_enabled():
thats what you mean. 
good point i will move the pop up to try_init.

2024-09-12 13:21 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +    from qtpy import QtWidgets
If you're not in headless mode, doesn't mean you have access to Qt.

2024-09-12 13:22 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +            if not is_headless_mode_enabled():
wait a moment this isnt really possible is it?
we need to stop the module from initializing in all cases including farm. 

If we set the module self.enabled to false we will never get to try_init.

2024-09-12 14:02 UTC, Lypsolon commented on package.py
> +version = "0.1.0-alpha-dev-pop1"
we can remove everything after dev no problem i just wanted to upload something to the server for a test thats why its there. 

let me remove the other things real quick.

2024-09-12 14:04 UTC, Lypsolon commented on package.py
> +version = "0.1.0-alpha-dev-pop1"
done via external commit.

2024-09-12 14:12 UTC, Lypsolon commented on client/ayon_usd/utils.py
> +    app = QtWidgets.QApplication()
fair enough. 
fixed in the last commit via a multi process for isolation.

2024-09-12 14:14 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +            if not HEADLESS_MODE_ENABLED:
fair enough is there an early place in the addon that is only run when ayon starts ? 
i believe try init is not run in headless as well you dont have a tray for the tray icon.

2024-09-12 14:21 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +            controller.start()
no its not showing 20 times there is an early return if higher up in the code. after the right usd lib is loaded it will not be shown again. 

and no its not the same as the popup the dialog is an normal QDialog.  

i can move it to a place that only runs at ayon startup but for that i need some docs or information on what the order and guarantee of calls on the addon is. 

right now i know that tray init is an option but you never answered if tray init actually runs in headless mode or when no tray is available.

2024-09-12 14:23 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +            controller.start()
there is an early return at line 79. the controller the ui etc will never be constructed if the usd lib is already downloaded. 

```py
        if not utils.is_usd_lib_download_needed(settings):
            print("usd is already downloaded")
            return


```

2024-09-12 14:26 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +            if not is_headless_mode_enabled():
honestly yes its should be as simple as you added an alpha to your bundle deal with it.
in my eyes your correct there ngl. 
 
but people in higher positions said there needs to be a button and a warning etc, and deciding this is above my pay grade.

@dee-ynput have fun.

2024-09-12 14:32 UTC, iLLiCiTiT commented on client/ayon_usd/addon.py
> +            controller.start()
Damn, I just found out this is in `tray_start` method. You don't need to check for availability of qt here at all.

2024-09-12 14:34 UTC, iLLiCiTiT commented on client/ayon_usd/utils.py
> +    p = multiprocessing.Process(target=_run, args=(title, message))
I don't think multiprocessing works in build AYON launcher.

2024-09-12 14:35 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +        self.enabled = True
done in external commit.

2024-09-12 14:35 UTC, Lypsolon commented on client/ayon_usd/utils.py
> +    p = multiprocessing.Process(target=_run, args=(title, message))
why?

2024-09-12 14:44 UTC, Lypsolon commented on client/ayon_usd/__init__.py
> +        import qtpy  # noqa: F401
yeah i saw that some where. 

do you know of any way? is there anything that ayon delivers to solve this ? 

anything like at all? 


is there an expectation that no addon will ever start up with gui? 



is there in general annyting that i can take as a guide, some docs a ClickUp document, an addon someting ?

2024-09-12 14:58 UTC, Lypsolon commented on client/ayon_usd/__init__.py
> +        import qtpy  # noqa: F401
isnt the crash the case for all the ayon tools tho ? 
i just tryed to start launcher after removing the qt bindings and welp dosnt work. 
is there an expectation how this should work ?

2024-09-13 06:17 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +            controller.start()
very nice but i guess it also means that at farm we would not download Usd libs ? 

is it reasonable to assume that when ayon runs on the fram it will be started with -headless flag ? 

if yes we could say that if we run headless mode we download in init or something better and if we are running none headless we can just go and do it in tray start ? 

or dose dose ayon expect a different behavior.

2024-09-13 06:19 UTC, Lypsolon commented on client/ayon_usd/addon.py
> +            if not is_headless_mode_enabled():
many thanks for the insight it was decided from Milan that we dont need the pop up so im gone just remove it.

2024-09-13 07:06 UTC, Lypsolon commented on client/ayon_usd/__init__.py
> +        import qtpy  # noqa: F401
im gonna leave it in for now so we test for qtpy to be availalbe and headless mode not enabled. 

it dosnt get the QtBindings error and i was not yet able to start ayon without the bindings installed, sooo cant really test in the direction. (with the addon disabled) 

but i would like to test if the error can be catched if you define it yourself before hand. cant imagine there is no way to catch it some how.

2024-09-13 07:38 UTC, Lypsolon commented on client/ayon_usd/__init__.py
> +        import qtpy  # noqa: F401
soo i did a little test and yes catching the `QtBindingsNotFoundError` error would be very complicated. 

but we can use importlib imports as they will cause an import error to be raised no meter what errors in the module.

do you have concerns with this ?, and a reason for the concerns ? 

```py
import importlib
HEADLESS_MODE = True
try:
    qtpy = importlib.import_module('qtpy')
    HEADLESS_MODE = False
except ImportError:
    print("qtpy is not installed. Please install qtpy and a Qt backend (PyQt5, PySide2, etc.).")
if not HEADLESS_MODE:
    from qtpy import QtWidgets
```

2024-09-13 10:14 UTC, iLLiCiTiT commented on client/ayon_usd/__init__.py
> +        import qtpy  # noqa: F401
1. You should move import to the function.
2. Bigger problem, you should not try to show any UI in `initialize`.

2024-09-16 09:59 UTC, Lypsolon commented on client/ayon_usd/utils.py
> +    p = multiprocessing.Process(target=_run, args=(title, message))
ahh i see. 
thanks for the explanation helps a lot for the future. 

im gonna remember the trick lucky for now we just dont need the Popup as Milan decided its not needed.

2024-09-16 13:02 UTC, Lypsolon commented on client/ayon_usd/__init__.py
> +        import qtpy  # noqa: F401
okay makes sens. 
i moved the import into try_start (PS: i thought you meant i should move it into the function that returns the GUI instance i misunderstood that quite a bit thats why i thought it would not help) 

the changes are in this PR as this PR will be closed as its not needed. 
https://github.com/ynput/ayon-usd/pull/45

2024-09-16 13:02 UTC, closed without merging